# Generated by Django 5.1.2 on 2024-10-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemType',
            field=models.CharField(default='men', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
